input_source: stdin
logging:
  file: logs/random_enumerative_weighted_topdown_20240805_200237_jmbl_fg_array_search_13.log
  level: ERROR
solver:
  name: z3
  timeout: 30000
synthesis_parameters:
  candidate_generation: top_down
  custom_grammar: '{ "S": [ ["ite", "B", "S", "S", 50], ["+", "S", "S", 30], ["-",
    "S", "S", 30], ["*", "S", "S", 35], ["neg", "S", 20], ["T", 10] ], "B": [ [">",
    "T", "T", 15], [">=", "T", "T", 15], ["<", "T", "T", 15], ["<=", "T", "T", 15],
    ["==", "T", "T", 15], ["!=", "T", "T", 15] ] }'
  initial_weight: 1.0
  max_candidates_at_each_depth: 200
  max_complexity: 7
  max_const: 2
  max_depth: 5
  max_iterations: 10000
  min_const: -2
  operation_costs:
    '*': 2
    +: 1
    '-': 1
    Neg: 1
    ite: 3
  random_seed: 1234
  randomise_each_iteration: false
  strategy: random_enumerative
  timeout: 30
  use_weighted_generator: true
  weight_multiplier: 1.2
