logging:
  level: ERROR
  file: "{root}/logs/partial_{datetime}_{problem}.log"

synthesis_parameters:
  strategy: partial
  candidate_generation: bottom_up
  max_iterations: 10000
  max_depth: 7
  max_complexity: 7
  random_seed: 1234
  randomise_each_iteration: false
  max_candidates_at_each_depth: 200
  timeout: 30
  min_const: -2
  max_const: 2
  operation_costs:
    '+': 1
    '-': 1
    '*': 2
    'ite': 3
    'neg': 1
  initial_weight: 1.0
  weight_multiplier: 1.0
  use_weighted_generator: false

solver:
  name: z3
  timeout: 30000

input_source: stdin