logging:
  level: WARNING
  file: "{root}/logs/random_enumerative_weighted_topdown_{datetime}_{problem}.log"
  metrics_file: "{root}/logs/metrics_random_enumerative_weighted_topdown_{datetime}_{problem}.json"

synthesis_parameters:
  strategy: random_enumerative
  candidate_generation: top_down
  max_iterations: 10000
  max_depth: 5
  max_complexity: 7
  random_seed: 1234
  randomise_each_iteration: false
  max_candidates_at_each_depth: 200
  timeout: 30
  min_const: -2
  max_const: 2
  operation_costs:
    '+': 1
    '-': 1
    '*': 2
    'ite': 3
    'Neg': 1
  initial_weight: 1.0
  weight_multiplier: 1.2
  use_weighted_generator: true
  custom_grammar: '{
    "S": [
      ["ite", "B", "S", "S", 50],
      ["+", "S", "S", 30],
      ["-", "S", "S", 30],
      ["*", "S", "S", 35],
      ["neg", "S", 20],
      ["T", 10]
    ],
    "B": [
      [">", "T", "T", 15],
      [">=", "T", "T", 15],
      ["<", "T", "T", 15],
      ["<=", "T", "T", 15],
      ["==", "T", "T", 15],
      ["!=", "T", "T", 15]
    ]
}'

solver:
  name: z3
  timeout: 30000

input_source: stdin