synthesis_parameters:
  max_iterations: 300
  operation_costs:
    '+': 1
    '-': 1
    '*': 3
    'If': 4
    'Neg': 2
  custom_grammar: '{"S": ["T", ["+", "S", "S"], ["-", "S", "S"]], "T": ["x", "y", "1", "2"]}'
logging:
  level: "DEBUG"