input_source: stdin
logging:
  file: /data/Documents/DataScience/Courses/Dissertation/logs/fast_enumerative_20240806_165731_arraysearch20.log
  level: ERROR
solver:
  name: z3
  timeout: 30000
synthesis_parameters:
  candidate_generation: fast_enumerative
  initial_weight: 1.0
  max_candidates_at_each_depth: 200
  max_complexity: 7
  max_const: 2
  max_depth: 7
  max_iterations: 10000
  min_const: -2
  operation_costs:
    '*': 2
    +: 1
    '-': 1
    Neg: 1
    ite: 3
  random_seed: 1234
  randomise_each_iteration: false
  strategy: fast_enumerative
  timeout: 30
  use_weighted_generator: false
  weight_multiplier: 1.0
