input_source: stdin
logging:
  file: /data/Documents/DataScience/Courses/Dissertation/logs/partial_20240815_174257_jmbl_fg_polynomial1.log
  level: WARNING
  metrics_file: /data/Documents/DataScience/Courses/Dissertation/logs/metrics_partial_20240815_174257_jmbl_fg_polynomial1.json
solver:
  name: z3
  timeout: 30000
synthesis_parameters:
  candidate_generation: bottom_up
  initial_weight: 1.0
  max_candidates_at_each_depth: 205
  max_complexity: 9
  max_const: 2
  max_depth: 9
  max_iterations: 50000
  min_const: -2
  operation_costs:
    '*': 4
    +: 2
    '-': 2
    ite: 6
    neg: 2
  random_seed: 1234
  randomise_each_iteration: false
  strategy: partial
  timeout: 30
  use_weighted_generator: false
  weight_multiplier: 1.0
