input_source: stdin
logging:
  file: /data/Documents/DataScience/Courses/Dissertation/logs/random_enumerative_topdown_20240812_215826_arraysearch19.log
  level: WARNING
  metrics_file: /data/Documents/DataScience/Courses/Dissertation/logs/metrics_random_enumerative_topdown_20240812_215826_arraysearch19.json
solver:
  name: z3
  timeout: 30000
synthesis_parameters:
  candidate_generation: top_down
  custom_grammar: '{ "S": [ "T", ["ite", "B", "S", "S"], ["+", "S", "S"], ["-", "S",
    "S"], ["*", "S", "S"], ["neg", "S"] ], "B": [ [">", "T", "T"], [">=", "T", "T"],
    ["<", "T", "T"], ["<=", "T", "T"], ["==", "T", "T"], ["!=", "T", "T"] ] }'
  initial_weight: 1.0
  max_candidates_at_each_depth: 200
  max_complexity: 7
  max_const: 2
  max_depth: 5
  max_iterations: 50000
  min_const: -2
  operation_costs:
    '*': 2
    +: 1
    '-': 1
    Neg: 1
    ite: 3
  random_seed: 1234
  randomise_each_iteration: false
  strategy: random_enumerative
  timeout: 30
  use_weighted_generator: false
  weight_multiplier: 1.0
